version: '3.4'

services:

  rabbitmq:
           image: rabbitmq:3-management-alpine
           container_name: 'rabbitmq'
           environment:
            RABBITMQ_DEFAULT_USER: admin
            RABBITMQ_DEFAULT_PASS: admin
           ports:
               - 5672:5672
               - 15672:15672
               - 1883:1883

           #command: 'rabbitmq-plugins enable rabbitmq_mqtt'
           #volumes:
             #  - ./rabbitmq/etc/:/etc/rabbitmq/
             #  - ./rabbitmq/data/:/var/lib/rabbitmq/
             #  - ./rabbitmq/log/:/var/log/rabbitmq/
           restart: unless-stopped